public enum EventKey
{
    RESET_TIME_AND_UPDATE_SCORE,
    HIDE_BOTTOM_AND_PUSH_UP_TITLE,
    SHOW_BOTTOM_AND_PUSH_UP_TITLE,
    LOAD_ACHIEVEMENT,
    SHOW_POPUP_END_GAME,
    SET_IMAGE_EGG_CURRENT,
    SET_IMAGE_EGG_MAX,
    CHECK_HAVE_STEP,
    SET_TYPE_TILE,
    BFS,
}